# Generated by Django 2.2.2 on 2020-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
