# Generated by Django 2.2.2 on 2020-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200508_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourorder',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
