# Generated by Django 2.2.2 on 2020-05-31 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200512_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('yourorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.yourorder')),
                ('price', models.IntegerField(null=True)),
            ],
            bases=('mainapp.yourorder',),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 5, 31)),
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 5, 31)),
        ),
    ]
