# Generated by Django 2.2.2 on 2020-05-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200531_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
