# Generated by Django 2.2.2 on 2020-06-01 06:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 6, 1)),
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 6, 1)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordereditems', models.CharField(max_length=255)),
                ('ordereddate', models.DateTimeField(default=datetime.date(2020, 6, 1))),
                ('houseno', models.CharField(max_length=15, null=True)),
                ('street', models.IntegerField(null=True)),
                ('locality', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(default='Hyderabad', max_length=255)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('price', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
