# Generated by Django 2.2.2 on 2020-06-09 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200604_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 6, 9)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 6, 9)),
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 6, 9)),
        ),
    ]
