# Generated by Django 2.2.2 on 2020-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_orderfood_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='category',
            field=models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20, null=True),
        ),
    ]
