# Generated by Django 2.2.2 on 2020-07-03 06:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200703_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('persons', models.IntegerField(default=1)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 7, 3, 6, 48, 5, 523174))),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Reservations are full!', 'Reservations are full!')], default='Pending...', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
