# Generated by Django 2.2.2 on 2020-07-03 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_bookingtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='datetime',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 3)),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 3, 7, 39, 14, 314586)),
        ),
    ]
