# Generated by Django 2.2.2 on 2020-07-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200703_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='phone',
        ),
    ]
