# Generated by Django 2.2.2 on 2020-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_remove_bookingtable_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
