# Generated by Django 2.2.2 on 2020-07-04 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_bookingtable_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 4)),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Reservations are full!', 'Reservations are full!')], default='Pending...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 7, 4)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 7, 4)),
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 7, 4)),
        ),
    ]
