# Generated by Django 2.2.2 on 2020-07-06 06:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20200704_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 6)),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='persons',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('6', '6'), ('8', '8'), ('10+', '10+')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='time',
            field=models.TimeField(choices=[('10 A.M', '10 A.M'), ('10:30 A.M', '10:30 A.M'), ('11 A.M', '11 A.M'), ('11:30 A.M', '11:30 A.M'), ('12 P.M', '12 P.M'), ('12:30 P.M', '12:30 P.M'), ('1 P.M', '1 P.M'), ('1:30 P.M', '1:30 P.M'), ('2 P.M', '2 P.M'), ('2:30 P.M', '2:30 P.M'), ('3 P.M', '3 P.M'), ('3:30 P.M', '3:30 P.M'), ('4 P.M', '4 P.M'), ('4:30 P.M', '4:30 P.M'), ('5 P.M', '5 P.M'), ('5:30 P.M', '5:30 P.M'), ('6 P.M', '6 P.M'), ('6:30 P.M', '6:30 P.M'), ('7 P.M', '7 P.M'), ('7:30 P.M', '7:30 P.M'), ('8 P.M', '8 P.M'), ('8:30 P.M', '8:30 P.M'), ('9 P.M', '9 P.M'), ('9:30 P.M', '9:30 P.M'), ('10 P.M', '10 P.M')], default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 7, 6)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 7, 6)),
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='ordereddate',
            field=models.DateTimeField(default=datetime.date(2020, 7, 6)),
        ),
    ]
