# Generated by Django 2.2.2 on 2020-07-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20200706_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='persons',
            field=models.CharField(choices=[('', 'Persons'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('6', '6'), ('8', '8'), ('10+', '10+')], default=1, max_length=20),
        ),
    ]
