# Generated by Django 2.2.2 on 2020-07-06 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20200706_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='persons',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
