# Generated by Django 2.2.2 on 2020-07-23 08:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20200719_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='orderedtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='orderedtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yourorder',
            name='orderedtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ordereddate',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordereddate',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='ordereddate',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
    ]
