# Generated by Django 2.2.2 on 2020-07-23 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20200723_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='ordereddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordereddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='ordereddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
