# Generated by Django 2.2.2 on 2020-07-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20200723_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourorder',
            name='orderedtime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
