# Generated by Django 2.2.2 on 2020-07-23 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20200723_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourorder',
            name='orderedtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
